name: "Danger JS"

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@11.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}