name: "Danger JS"

on: [pull_request]

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: 
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@11.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}